### PR TITLE
Inheritance demonstrated 

### PR DESCRIPTION
**Pull request by priyda**
this contract  explains inheritance and interface in solidity.

### CODE REVIEW

**Comment by mkubdev** [comment]
Hey @priyda, that'll be awesome if you can explain your code. :)

**Comment by priyda** [comment]
> Hey @priyda, that'll be awesome if you can explain your code. :)

Hello @mkubdev can you please review again, made few changes

**Comment by priyda** [comment]
> > Hey @priyda, that'll be awesome if you can explain your code. :)
> 
> Hello @mkubdev can you please review again, made a few changes
@mkubdev - Do I need to make any more changes to merge this PR?

**Comment by priyda** [comment]
> > > Hey @priyda, that'll be awesome if you can explain your code. :)
> > 
> > 
> > Hello @mkubdev can you please review again, made a few changes
> > @mkubdev - Do I need to make any more changes to merge this PR?
@mkubdev - is it alright to merge?

**Review by mkubdev — APPROVED** [review]

**Pull request merged**
