### PR TITLE
fix: AutoPrettier changes not being pushed

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Fix AutoPrettier changes not being pushed.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/Solidity/pull/62"></a>

### CODE REVIEW

**Comment by Panquesito7** [comment]
Okay, I was having various issues with the workflows and hopefully, the latest commit fixes it. :)

**Comment by mkubdev** [comment]
Is this automated with workflow?

**Comment by Panquesito7** [comment]
> Is this automated with workflow?

Yep.

**Review by mkubdev — APPROVED** [review]
LGTM. Thanks David!

**Pull request merged**
