### PR TITLE
feat: add basic mathematics algo for the solidity repos

### PR DESCRIPTION
**Pull request by mkubdev**
Hello theAlgorithms.

My PR contain basics solidity mathematics algorithms.

Have a good day ✨

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Don't know anything about Solidity, but this is good to go 🚀 Thanks! 🎉
Anyways, I'll request a review from Shubham and Ritvik. 😃

**Comment by mkubdev** [comment]
> Don't know anything about Solidity, but this is good to go 🚀 Thanks! 🎉
Anyways, I'll request a review from Shubham and Ritvik. 😃

Sure! :D

**Review by shuklaritvik06 — APPROVED** [review]
Looks Good to me, Let's wait for Shubham's review :)

**Comment by mkubdev** [comment]
@KukretiShubham this PR is still pending 🐉

**Review by KukretiShubham — APPROVED** [review]
LGTM 🚀 
Sorry for the delayed review. My system broke last night.

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
