### PR TITLE
Contract to explain how to use struct data type in voting app

### PR DESCRIPTION
**Pull request by priyda**
this contract is to explain how struct and mapping can be used in making a voting app.

### CODE REVIEW

**Comment by mkubdev** [comment]
Hey @priyda, that'll be awesome if you can explain your code. :)

**Comment by priyda** [comment]
> Hey @priyda, that'll be awesome if you can explain your code. :)

thank you for the feedback and Should I make more comments in the code  or here in pull request?

**Comment by priyda** [comment]
> > Hey @priyda, that'll be awesome if you can explain your code. :)
> 
> 

@mkubdev  thank you for the feedback . Should I make more comments in the code or here in pull request?

**Review by mkubdev — APPROVED** [review]
LGTM

**Pull request merged**
